databases:
  - name: taskmanagerdb
    plan: free
    databaseName: taskmanager
    user: taskmanager

services:
  - type: web
    plan: free
    name: taskmanager
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn task_manager.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: taskmanagerdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
