# Generated by Django 5.0.6 on 2024-05-17 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='tasks',
        ),
        migrations.DeleteModel(
            name='TaskLabelRelationship',
        ),
    ]
