# Generated by Django 5.0.6 on 2024-05-17 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0002_remove_label_tasks_delete_tasklabelrelationship'),
        ('tasks', '0003_alter_task_description_alter_task_executor'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskLabelRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='labels.label')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(through='tasks.TaskLabelRelationship', to='labels.label'),
        ),
    ]
