name: CI
on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: install poerty
        uses: snok/install-poetry@v1

      - name: install dependencies
        run: poetry install
      
      - name: linter
        run: make lint
      
      - name: Run tests and generate coverage report
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build
          poetry run pytest --cov=task_manager --cov-report=xml
          ./cc-test-reporter after-build --exit-code $?
        env:
          CODECLIMATE_REPO_TOKEN: ${{ secrets.CODECLIMATE_REPO_TOKEN }}
          CI: true